### CASA0002

# Urban Simulation
***
## Python Review Practical
***

### Many kinds of Python
#### The Jupyter Notebook

The easiest way to get started using Python, and one of the best for research data work, is the Jupyter Notebook.

In the notebook, you can easily mix code with discussion and commentary, and mix code with the results of that code;
including graphs and other data visualisations.

Jupyter notebooks consist of discussion cells, referred to as "markdown cells", and "code cells", which contain Python. This document has been created using Jupyter notebook, and this very cell is a **Markdown Cell**. 

In [14]:
print("This cell is a code cell")

This cell is a code cell


### Typing code in the notebook

When working with the notebook, you can either be in a cell, typing its contents, or outside cells, moving around the notebook.

* When in a cell, press escape to leave it. When moving around outside cells, press return to enter.
* Outside a cell:
  * Use arrow keys to move around.
  * Press `b` to add a new cell below the cursor.
  * Press `m` to turn a cell from code mode to markdown mode.
  * Press `shift`+`enter` to calculate the code in the block.
  * Press `h` to see a list of useful keys in the notebook.
* Inside a cell:
  * Press `tab` to suggest completions of variables. (Try it!)
  
*Supplementary material*: Learn more about [Jupyter notebooks](https://jupyter.org/).

**Python** is an extremely popular and versatile high-level programming language that was created by Guido Van Rossum in the 90.
It is a general-purpose language focusing on procedural programming (which we will focus on) and object oriented programming. 

In [16]:
# let's start with printing "hello world"
print ("hello world")

hello world


### Comments

Code after a `#` symbol doesn't get run.

In [25]:
print("This runs") # print "This doesn't"
# print This doesn't either

This runs


### Variables assignment

A value/object stored in computer’s memory ”=“

>x = "hello world"


When we generate a result, the answer is displayed, but not kept anywhere.

In [27]:
2*3

6

If we want to get back to that result, we have to store it. We put it in a box, with a name on the box. This is a **variable**.

In [29]:
result = 2*3
print(result)

6


### Objects and types

An object, like `result`, has a type. Here we see that the object 'result' has type "int".
`int` means a integer object.

In [30]:
type(result)

int

### Basic Data Types

Strings(str): an ordered sequence of characters. 
>Sample_string=“hello world”

Integers(int): Positive/Negative whole numbers 
>sample_int = 3619

Floats(float): Real number with floating point. 
>Sample_float= 1.126

Boolean(bool): either True or False
>Sample_bool = True

### Composite data-types

Sequence : list, tuple, range

> l1 = []

Mapping : dict

> d1 = {'stephen':'London'}

Sets: set

> s1 = {1,10}


In [36]:
# you can access each character of a string through an index

# first element
x = 'hello world'
print(x[0])

# second element
print (x[1])

# slice
print (x[0:5])

h
e
hello


### Lists
A list is a mutable ordered sequence of items. The items of a list are arbitrary objects.
> mylist = []

In [1]:
# lists are defined by [] or list()
list1=[1,2,3,4,5,6]
print(list1)
# lists can be sliced
print (list1[1])
print (list1[2:])

# list methods - pop and append
list1=[1,2,3,4,5,6]

#we can add an element to the end of a list with .append
list1.append(7)

#we can remove an element from the list with .pop
list1.pop(2)
print (list1)

[1, 2, 3, 4, 5, 6]
2
[3, 4, 5, 6]
[1, 2, 4, 5, 6, 7]


### tuples

an ordered immutable collection of one or more items.
> my_tuple = ('london', 'new york')

In [3]:
# tuples are defined by () or tuple()
tup1=(1,2,3,4)

# tuples are immutable
tup1[0]=1

TypeError: 'tuple' object does not support item assignment

### dictionary

A dictionary is an unordered collection of data in a key:value pair.

> my_dict = {'key1': 10}

In [4]:
# dicts are defined by {key:vaue} or dict()
d1 = {}
d1['course']="urban simulation"
d1['duration']=10
d1['location']="London"
print(d1)

#access item in dictionary
print(d1['course'])

{'course': 'urban simulation', 'duration': 10, 'location': 'London'}
urban simulation


### sets

Unordered collections of unique elements.

>sample_set = {"Camden","Hackney","Westminster"}

In [6]:
#sets are defined by {} or set()
set1 = {1,1,1,1,10}
set1

{1, 10}

In [7]:
# sets operations

set1={1,1,1,1,10}
set2={1,1,1,1,20}

print (set1.intersection(set2))

print (set1.union(set2))

print (set1.difference(set2))

{1}
{1, 10, 20}
{10}


### Range

Immutable sequence of numbers and is commonly used for looping a specific number of times in a for loop. Its three parameters are the beginning of range, the end of range and its increments.

> range(1,10,1)

In [16]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

## Algorithms

An algorithm is a sequence of operations that need to be performed to solve a problem or carry out a process.


## Program
A program is a series of software instructions to control the operation of a computer. A program can contain multiple algorithms.



In [8]:
# a simple program
width = 2
height = 3
area = width * height
print(area)

6


### Basic Arithmatic Operations

In python there are a number of basic arithmatic operations

    +    addition
    -    subtraction
    *    multiplication
    /    division
    **   exponentiation
    %    modulo (remainder of division)
    ==   equality (true/false)

In [11]:
# perform basic mathematic operations on the variables
a = 20
b = 60
c = 80
z = ((a+b+c)/20)**2
print (z)


64.0


### Functions

We can wrap code up in a **function**, so that we can repeatedly get just the information we want.

A function are statements which is executed when it is called. It uses the keyword def().

> def newFunc():

In [12]:
def area(width, height):
    return width * height

In [13]:
area(5, 12)

60

### Control Structure

Branching : if/else

Loop/Iteration : for/in , while

#### If statement
Conditional Statement in Python are handled by the IF statement.

In [21]:
### if/else conditions
steps=9
if steps==10:
    print ("True")
else:
    print ("False")

False


#### for statement
For statements are used when you have a block of code which you want to repeat. The **For** keyword is used to loop over an iteratable object such as strings, lists, range.

In [23]:
# list as an iterator
list1=[1,2,3,4,5,6]
for i in list1:
    print (i)

1
2
3
4
5
6


#### while statement

While statement is used when a condition needs to be checked for each iteration, or to repeat a block of code forever.

In [25]:
### while loops
steps=10
i=0
while i<steps:
    print (f'hello world: {i}')
    i=i+1

hello world: 0
hello world: 1
hello world: 2
hello world: 3
hello world: 4
hello world: 5
hello world: 6
hello world: 7
hello world: 8
hello world: 9


### Importing Libraries

Research programming is all about using libraries: tools other people have provided programs that do many cool things.
By combining them we can feel really powerful but doing minimum work ourselves. The python syntax to import someone else's library is "import".

In [26]:
import geopy # A python library for investigating geographic information.
# https://pypi.org/project/geopy/

# get coordinates of cambridge
geocoder = geopy.geocoders.Nominatim(user_agent='CASA0002')
geocoder.geocode('Cambridge')

Location(Cambridge, Cambridgeshire, East of England, England, United Kingdom, (52.197584649999996, 0.13915373736874398, 0.0))

### Classes: objects in python

Everything is an object in Python which are defined using classes. These are defined by the keyword class.

> class myClass:

Functions within objects are called methods. We can access these with a dot.

> "hello world!".upper()

In [54]:
class City:
    def __init__(self, name, pop, area):
        self.name = name
        self.population = pop
        self.area = area
        self. density = pop/area
    def info(self):
        print(f'name: {self.name}, population: {self.population}, area: {self.area}, density {self.density}')

In [55]:
london = City('London', 8961989, 1572)

In [57]:
london.info()

name: London, population: 8961989, area: 1572, density 5701.010814249364


## Numpy

Numpy is the fundamental package for scientific computing with Python. It provides numerical functions on ndarray which are fixed size n-dimensional array data structures. Numpy is implemented in C where its memory is more efficiently stored.

>import numpy as np

In [58]:
### let's first import the numpy library
import numpy as np

### Numpy Arrays - Vectors
> $x \in \mathbb{R}^n$
 
one dimensional ndarray represent a vector of elements.
> x = np.array([2,3,4])

In [60]:
### make a 1d array
array1=np.array([1,1,1,1,1,1,1,2,2,3,4,5,6,7,8,10])

print (array1.ndim)
print (array1.size)
print (array1.shape)

# similar to python data type (int,float,bool)
print (array1.dtype)

1
16
(16,)
int32


### Numpy Arrays - Matrix

> $m \in \mathbb{R}^{n*m}$

two dimensional ndarray represents a matrix of elements.

> array2 = np.array([[1, 2, 3], [4, 5, 6]])

In [62]:
### make a 2d array
array2=np.array([[1,1,1,1,1,1,1,2,2,3,4,5,6,7,8,10],
                 [1,1,1,1,1,1,1,2,2,3,4,5,6,7,8,10]])

print (array2.ndim)
print (array2.size)
print (array2.shape)
print (array2.dtype)

2
32
(2, 16)
int32


### Numpy Arrays - Multidimensional arrays (Tensors)

We can also use ndarray to create multidimensional arrays. These are often useful to represent tensors.

Images for example can be represented as a three-dimensional array, where the shape = (channel,height, width).

>array3 = np.array([[[1, 2],[4, 5]],[[2, 5], [6, 4]],[[2, 5],[6, 4]]])

In [63]:
### make a 3d array
array3=np.array( [[[1, 2],
                   [4, 5]],
                  [[2, 5],
                   [6, 4]],
                  [[2, 5],
                   [6, 4]]])

print (array3.ndim)
print (array3.size)
print (array3.shape)
print (array3.dtype)

3
12
(3, 2, 2)
int32


### index, sort and reshape arrays

In [70]:
array1=np.array([1,1,8,1,1,5,1,2,2,3,4,5,6,7,8])

### indexing
print (array1[0])

### slicing
print (array1[0:10])

1
[1 1 8 1 1 5 1 2 2 3]


In [71]:
### sort the array
np.sort(array1)

array([1, 1, 1, 1, 1, 2, 2, 3, 4, 5, 5, 6, 7, 8, 8])

In [76]:
# reshape array
array2 = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(array2)
# as 3x2 ndarray
array3 = array2.reshape(3,2)
print (array3)

print (array2.shape)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
(2, 3)


In [77]:
# transpose array
print(array2.T)

[[1 4]
 [2 5]
 [3 6]]


In [79]:
# flatten array
print (array3)
print (array3.flatten())

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


### mathematical function
* np.sum - Compute sum of elements
* np.prod - Compute product of elements
* np.mean - Compute mean of elements
* np.std - Compute standard deviation
* np.var - Compute variance
* np.min - Find minimum value
* np.max - Find maximum value
* np.argmin - Find index of minimum value
* np.argmax - Find index of maximum value
* np.median - Compute median of elements

In [84]:
# arithmatic operations on arrays 
array0 = np.array([1, 2, 3])

# these operation are 'broadcasted' to the array
# see https://numpy.org/doc/stable/user/basics.broadcasting.html
print (array0 + 1)
print (array0 * 2)
print (array0 ** 2)

[2 3 4]
[2 4 6]
[1 4 9]


In [86]:
# define array
array2=np.array([[1,1,1,1,1,1,1,2,2,3,4,5,6,7,8,10],
                 [1,1,1,1,1,1,1,2,2,3,4,5,6,7,8,10]])

# sum across columns 
print (np.sum(array2,axis=0))

# sums across rows 
print (np.sum(array2,axis=1))

[ 2  2  2  2  2  2  2  4  4  6  8 10 12 14 16 20]
[54 54]


### special arrays

In [88]:
### make an empty arrays of zeroes with shape (10)
print (np.zeros(10))

### make an empty arrays of ones with shape (10)
print (np.ones(10))

### make an array of random numbers with shape (3,2)
print (np.random.rand(3,2))

### an Identity matrix where the entries of the diagonals are 1
print (np.eye(3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0.93216983 0.42788755]
 [0.84390891 0.7492732 ]
 [0.46776845 0.48817346]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### numerical operations

In [91]:
# dot product between two arrays (product-sum between the two arrays)
rv = np.array([1,2,3])
cv = np.array([4,5,6])
np.dot(rv,cv)

32

In [92]:
array1D=np.array([1,1,1,1,1,1,1,2,2,3,4,5,6,7,8])
array2D=np.array([[1,1,1,1,1,1,1,2,2,3,4,5,6,7,8],
                 [1,1,1,1,1,1,1,2,2,3,4,5,6,7,8]])

np.matmul(array2D,array1D)

array([214, 214])

### References

* Python for Data Analysis: Data Wrangling with Pandas, NumPy, and Ipython (Wes McKinney)


* Python Official Tutorial https://docs.python.org/3/tutorial/index.html


* John V. Guttag. Introduction to Computation and Programming Using Python. MIT Press 2013. 
